[llvm]
ninja = true
targets = "X86"
experimental-targets = "WebAssembly"

[build]
build = "x86_64-unknown-linux-gnu"
host = ["x86_64-unknown-linux-gnu"]
target = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

docs = false
submodules = false
fast-submodules = false

[rust]
backtrace = false
lld = true
clang = true
